<a href="https://colab.research.google.com/github/Samir-atra/Barbados_Traffic_Analysis_Challenge_dev/blob/main/notebooks/mediapipe_video_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Mediapipe video analysis**
## Best run on GPU

# Imports

In [1]:
import os
import cv2
import subprocess
import pandas as pd
from google.cloud import storage
from collections import defaultdict
from IPython.display import Video, display
from google.colab.patches import cv2_imshow

# Set Up

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
%%capture
!pip install mediapipe
!wget -q -O efficientdet.tflite -q https://storage.googleapis.com/mediapipe-models/object_detector/efficientdet_lite0/float16/1/efficientdet_lite0.tflite

In [4]:
!gcloud auth login # Authenticates your identity for general gcloud CLI command use e.g. gcloud storage cp, gcloud compute, gsutil
!gcloud auth application-default login # Authenticates your environment for API access e.g., storage.Client()

Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=32555940559.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&state=aAsyoqme7iRC9ye4V17FmqE9gbiaS3&prompt=consent&token_usage=remote&access_type=offline&code_challenge=yCgTMSdOtgUaHWP2ki6WHP72Fdwpc8yG-n4YUkMmI-g&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0ATX87lNMxPAbg-ApynUFrQAvZp96Tfkx-gLvuKkxKzOI0VTFZV1ySJ5UEWrnyGosXoRjZg

You are now logged in as [samiratra95@gmail.com].
Your current project is [None].  You can change this setting by running:
  $ gcloud config set project PROJECT_ID


To take a quick anonymous survey, run:
  $ gcloud survey

Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=kOuFf6TNFvHaygu6QtVL8OqfyX2InE&prompt=consent&token_usage=remote&access_type=offline&code_challenge=RRh8lWW-qRYs9ByWpVql4UKvukiSqbiNfbGeZ068Wbg&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0ATX87lMKxbeh-EHgZJvct5VYZpQ7c561Ros2KMf9hZ-AMEH7ARPwC2T_w1wVNzvY7HMRLw

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.

In [5]:
client = storage.Client(project="brb-traffic")

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:108: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [6]:
base_dir = "/"
bucket_name = 'brb-traffic'
video_path='videos'
os.makedirs(video_path, exist_ok=True)

# Read Data

In [8]:
# Load the dataset
train = pd.read_csv(os.path.join(base_dir, '/content/Train.csv'))

# Extract camera ID and reconstruct the video path
def extract_camera_path(video):
    parts = video.split('/')
    filename = parts[-1]
    camera_id = filename.split('_')[0]
    return f"{camera_id}/{filename}"

train['videos'] = train['videos'].apply(extract_camera_path)

# Display shape and preview
display(train.shape, train.head())

(16076, 14)

,responseId,view_label,ID_enter,ID_exit,videos,video_time,datetimestamp_start,datetimestamp_end,date,signaling,congestion_enter_rating,congestion_exit_rating,time_segment_id,cycle_phase
0,zYkHaeOdB7XOnvgP3YW5kQs,Norman Niles #1,time_segment_0_Norman Niles #1_congestion_ente...,time_segment_0_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-00-45.mp4,2025-10-20 06:00:45,2025-10-20 06:00:45,2025-10-20 06:01:44,2025-10-20,none,free flowing,free flowing,0,train
1,NYsHaeCRLq-vnvgPjoXZqA0,Norman Niles #1,time_segment_1_Norman Niles #1_congestion_ente...,time_segment_1_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-01-45.mp4,2025-10-20 06:01:45,2025-10-20 06:01:45,2025-10-20 06:02:44,2025-10-20,none,free flowing,free flowing,1,train
2,A40HaYT8KNm7nvgPq8e12AU,Norman Niles #1,time_segment_2_Norman Niles #1_congestion_ente...,time_segment_2_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-02-45.mp4,2025-10-20 06:02:45,2025-10-20 06:02:45,2025-10-20 06:03:00,2025-10-20,none,free flowing,free flowing,2,train
3,EIsHaanDMK-vnvgPjoXZqA0,Norman Niles #1,time_segment_3_Norman Niles #1_congestion_ente...,time_segment_3_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-03-45.mp4,2025-10-20 06:03:45,2025-10-20 06:03:45,2025-10-20 06:04:44,2025-10-20,none,free flowing,free flowing,3,train
4,RYsHafSeMaqpmecP5vCV0AQ,Norman Niles #1,time_segment_4_Norman Niles #1_congestion_ente...,time_segment_4_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-04-45.mp4,2025-10-20 06:04:45,2025-10-20 06:04:45,2025-10-20 06:04:59,2025-10-20,none,free flowing,free flowing,4,train

In [9]:
ss = pd.read_csv(os.path.join(base_dir,'/content/SampleSubmission.csv'))
display(ss.shape,ss.head())

(880, 3)

,ID,Target,Target_Accuracy
0,time_segment_129_Norman Niles #1_congestion_en...,free flowing,free flowing
1,time_segment_130_Norman Niles #1_congestion_en...,heavy delay,heavy delay
2,time_segment_131_Norman Niles #1_congestion_en...,free flowing,free flowing
3,time_segment_132_Norman Niles #1_congestion_en...,heavy delay,heavy delay
4,time_segment_133_Norman Niles #1_congestion_en...,free flowing,free flowing

In [ ]:
# test = pd.read_csv(os.path.join(base_dir,'TestInputSegments.csv'))
# display(test.shape,test.head())

# Download files from a google cloud storage

In [15]:
blobs=train.videos.tolist()[200:300]
blobs

['normanniles1/normanniles1_2025-10-20-10-04-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-05-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-06-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-07-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-08-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-09-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-10-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-11-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-12-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-13-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-14-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-16-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-17-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-18-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-19-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-20-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-21-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-22-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-23-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-24-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-25-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-26-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-27-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-28-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-29-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-30-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-31-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-32-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-33-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-34-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-35-45.mp4',
 'normanniles1/normanniles1_2025-10-20-10-59-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-00-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-01-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-02-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-03-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-04-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-05-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-06-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-07-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-08-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-09-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-10-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-11-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-12-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-13-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-14-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-15-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-16-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-17-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-18-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-19-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-20-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-21-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-22-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-23-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-24-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-25-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-26-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-27-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-28-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-29-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-30-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-31-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-32-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-33-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-34-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-35-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-36-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-37-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-38-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-39-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-40-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-41-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-42-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-43-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-44-45.mp4',
 'normanniles1/normanniles1_2025-10-20-11-45-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-09-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-10-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-11-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-12-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-13-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-14-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-15-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-16-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-17-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-18-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-19-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-20-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-21-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-22-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-23-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-24-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-25-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-26-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-27-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-28-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-29-45.mp4',
 'normanniles1/normanniles1_2025-10-20-12-30-45.mp4']

In [16]:
from google.api_core.exceptions import NotFound

for blob_name in blobs:
    blob = client.bucket(bucket_name).blob(blob_name)
    file_name = os.path.basename(blob_name)  # get last part after '/'
    local_path = os.path.join(video_path, file_name)

    print("Downloading:", blob_name)
    try:
        blob.download_to_filename(local_path)
        print("✅ Downloaded to:", local_path)
    except NotFound:
        print(f"❌ Error: {blob_name} not found in bucket {bucket_name}. Skipping.")
    except Exception as e:
        print(f"❌ An unexpected error occurred while downloading {blob_name}: {e}")

Downloading: normanniles1/normanniles1_2025-10-20-10-04-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-04-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-05-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-05-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-06-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-06-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-07-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-07-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-08-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-08-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-09-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-09-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-10-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-10-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-11-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-11-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-12-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-12-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-13-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-13-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-14-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-14-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-16-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-16-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-17-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-17-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-18-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-18-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-19-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-19-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-20-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-20-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-21-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-21-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-22-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-22-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-23-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-23-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-24-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-24-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-25-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-25-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-26-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-26-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-27-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-27-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-28-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-28-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-29-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-29-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-30-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-30-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-31-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-31-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-32-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-32-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-33-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-33-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-34-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-34-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-35-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-35-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-10-59-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-10-59-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-00-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-00-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-01-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-01-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-02-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-02-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-03-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-03-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-04-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-04-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-05-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-05-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-06-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-06-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-07-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-07-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-08-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-08-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-09-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-09-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-10-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-10-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-11-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-11-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-12-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-12-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-13-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-13-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-14-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-14-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-15-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-15-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-16-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-16-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-17-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-17-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-18-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-18-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-19-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-19-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-20-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-20-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-21-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-21-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-22-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-22-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-23-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-23-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-24-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-24-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-25-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-25-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-26-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-26-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-27-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-27-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-28-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-28-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-29-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-29-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-30-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-30-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-31-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-31-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-32-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-32-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-33-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-33-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-34-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-34-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-35-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-35-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-36-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-36-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-37-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-37-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-38-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-38-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-39-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-39-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-40-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-40-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-41-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-41-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-42-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-42-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-43-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-11-43-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-11-44-45.mp4
❌ Error: normanniles1/normanniles1_2025-10-20-11-44-45.mp4 not found in bucket brb-traffic. Skipping.
Downloading: normanniles1/normanniles1_2025-10-20-11-45-45.mp4
❌ Error: normanniles1/normanniles1_2025-10-20-11-45-45.mp4 not found in bucket brb-traffic. Skipping.
Downloading: normanniles1/normanniles1_2025-10-20-12-09-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-09-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-10-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-10-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-11-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-11-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-12-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-12-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-13-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-13-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-14-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-14-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-15-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-15-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-16-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-16-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-17-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-17-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-18-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-18-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-19-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-19-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-20-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-20-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-21-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-21-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-22-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-22-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-23-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-23-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-24-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-24-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-25-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-25-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-26-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-26-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-27-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-27-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-28-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-28-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-29-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-29-45.mp4
Downloading: normanniles1/normanniles1_2025-10-20-12-30-45.mp4
✅ Downloaded to: videos/normanniles1_2025-10-20-12-30-45.mp4

# Delete videos

In [ ]:
import os
import shutil # Import shutil, though we'll adjust its usage

# Get the list of filenames that should exist in video_path
relevant_filenames = {os.path.basename(blob_path) for blob_path in blobs}

# Get the list of actual files in the video_path directory
current_video_files = os.listdir(video_path)

print(f"Number of relevant files (from blobs): {len(relevant_filenames)}")
print(f"Number of files currently in video_path: {len(current_video_files)}")

# Iterate through current files and delete those that ARE relevant
print("Deleting relevant videos from the directory...")
for filename in current_video_files:
    file_to_delete = os.path.join(video_path, filename)
    is_file = os.path.isfile(file_to_delete)
    is_mp4 = filename.lower().endswith('.mp4')

    print(f"Checking {filename}: Is relevant={filename in relevant_filenames}, Is file={is_file}, Is MP4={is_mp4}")

    if filename in relevant_filenames: # Condition inverted to delete relevant files
        if is_file and is_mp4:
            os.remove(file_to_delete)
            print(f"Deleted relevant MP4 file: {file_to_delete}")
    # else:
        # print(f"Keeping irrelevant file: {filename}") # Uncomment to see which files are kept

# Play some videos downloaded earlier

In [ ]:
def show_video(video_path, trim=False, duration=10, width=800):
    """
    Convert (and optionally trim) a video, suppress ffmpeg output, and display it inline.
    Parameters:
        video_path (str): Path to the input video file.
        trim (bool): Whether to trim the video to a short preview (default False).
        duration (int): Duration in seconds if trimming (default 10).
        width (int): Display width in pixels (default 800).
    """
    output_path = "preview.mp4"

    # Build ffmpeg command
    cmd = ["ffmpeg", "-i", video_path]
    if trim:
        cmd += ["-t", str(duration)]
    cmd += [output_path, "-y"]  # overwrite existing

    # Run ffmpeg silently (no stdout/stderr)
    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    # Display the video inline
    display(Video(output_path, width=width, embed=True))

In [ ]:
counter = 0
for video in os.listdir(video_path):
    full_path = os.path.join(video_path, video)
    show_video(full_path)  # display the full video
    #show_video("normanniles1_2025-10-20-06-01-45.mp4", trim=True)     # 10s preview
    #show_video("normanniles1_2025-10-20-06-01-45.mp4", trim=True, duration=5)  # 5s preview
    counter += 1
    if counter == 2:
        break

# Mediapipe object detection setup

In [17]:
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import cv2
import os
from google.colab.patches import cv2_imshow
import pandas as pd # Import pandas for DataFrame creation
import re # Import regex for timestamp extraction


model_path = '/absolute/path/to/lite-model_efficientdet_lite0_detection_metadata_1.tflite'

# Populate congestion_map from the train DataFrame
congestion_map = {}
for index, row in train.iterrows():
    # The 'videos' column in train DataFrame contains paths like 'normanniles1/normanniles1_2025-10-20-10-04-45.mp4'
    # os.path.basename extracts 'normanniles1_2025-10-20-10-04-45.mp4'
    video_full_path = row['videos']
    video_filename_base = os.path.basename(video_full_path)
    congestion_map[video_filename_base] = {
        'congestion_enter_rating': row['congestion_enter_rating'],
        'congestion_exit_rating': row['congestion_exit_rating']
    }

BaseOptions = mp.tasks.BaseOptions
ObjectDetector = mp.tasks.vision.ObjectDetector
ObjectDetectorOptions = mp.tasks.vision.ObjectDetectorOptions
VisionRunningMode = mp.tasks.vision.RunningMode

options = ObjectDetectorOptions(
    base_options=BaseOptions(model_asset_path='/content/efficientdet.tflite', delegate=BaseOptions.Delegate.GPU),
    max_results=-1,
    score_threshold=0.5,
    running_mode=VisionRunningMode.VIDEO,
    category_allowlist= ["person", "truck", "car", "motorcycle", "bus"],
    )

# Initialize detector ONCE outside the loop
detector = ObjectDetector.create_from_options(options)

all_video_results = [] # List to store results for all videos
cumulative_timestamp_ms = 0 # Initialize a global cumulative timestamp

# Get list of video files and sort them by timestamp
def extract_timestamp_from_filename(filename):
    match = re.search(r'\d{4}-\d{2}-\d{2}-\d{2}-\d{2}-\d{2}', filename)
    if match:
        return match.group(0)
    return filename # Return original name if no timestamp found, for stable sorting

video_files_in_dir = [f for f in os.listdir(video_path) if f.lower().endswith(('.mp4', '.avi', '.mov', '.mkv'))]
sorted_video_files = sorted(video_files_in_dir, key=extract_timestamp_from_filename)

try:
    for video_file_name in sorted_video_files:
        # Skip non-video files like .ipynb_checkpoints
        if not video_file_name.lower().endswith(('.mp4', '.avi', '.mov', '.mkv')):
            print(f"Skipping non-video file: {video_file_name}")
            continue

        # Initialize objects dictionary for each video
        objects = {"car_left":0,"car_right":0,"truck_left":0,"truck_right":0,"motorcycle_left":0,"motorcycle_right":0,"person_left":0,"person_right":0,"bus_left":0,"bus_right":0}

        # Retrieve congestion ratings
        congestion_info = congestion_map.get(video_file_name, {'congestion_enter_rating': 'unknown', 'congestion_exit_rating': 'unknown'})
        enter_rating = congestion_info['congestion_enter_rating']
        exit_rating = congestion_info['congestion_exit_rating']

        full_path = os.path.join(video_path, video_file_name)
        cap = cv2.VideoCapture(full_path)
        video_file_fps = cap.get(cv2.CAP_PROP_FPS)
        frame_duration_ms = int(1000 / video_file_fps) if video_file_fps > 0 else 0 # Calculate duration of one frame for this video

        if not cap.isOpened():
            print(f"Error: Could not open video file {full_path}")
            continue

        print(f"Processing video: {video_file_name}")
        frame_index_within_video = 0 # Keeping this for local count if needed for other logic
        while True: # Loop until break
            ret, frame = cap.read()
            if ret:
                # Get frame dimensions
                frame_height, frame_width, _ = frame.shape
                frame_midpoint_x = frame_width / 2
            else: # Use else for consistency with if not ret
                break

            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb_frame)

            # Use the global cumulative timestamp
            detection_result = detector.detect_for_video(mp_image, cumulative_timestamp_ms)

            # Increment the global cumulative timestamp for the next frame
            cumulative_timestamp_ms += frame_duration_ms

            for detection in detection_result.detections:
                bbox = detection.bounding_box

                category_name = detection.categories[0].category_name if detection.categories else "Unknown"
                score = round(detection.categories[0].score, 2) if detection.categories else 0.0

                # Calculate object's horizontal center for every detection
                object_center_x = bbox.origin_x + bbox.width / 2
                # Classify as 'left' or 'right' for every detection
                position_label = "left" if object_center_x < frame_midpoint_x else "right"

                if str(category_name) in["person", "truck", "car", "motorcycle", "bus"] and score >= 0.57:
                    # Update corresponding count only if criteria met
                    object_key = f'{category_name}_{position_label}'
                    if object_key in objects: # Ensure key exists before incrementing
                        objects[object_key] += 1

            # cv2_imshow(annotated_frame) # Display the annotated frame (commented out in original, keeping it that way)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
            frame_index_within_video += 1 # Increment local frame index
        print(f"Objects detected in {video_file_name}: {objects}")
        print(f"Congestion Enter Rating: {enter_rating}, Congestion Exit Rating: {exit_rating}")

        # Store results for the current video
        video_data = {
            'video_filename': video_file_name,
            'congestion_enter_rating': enter_rating,
            'congestion_exit_rating': exit_rating,
        }
        video_data.update(objects) # Add object counts to the dictionary
        all_video_results.append(video_data)

        cap.release() # Release the capture object after processing each video
        cv2.destroyAllWindows() # Close any OpenCV windows (important for local execution environments)
finally:
    # Close the detector after all videos are processed
    detector.close()

# Convert the list of dictionaries to a Pandas DataFrame
results_df = pd.DataFrame(all_video_results)
print("\n--- Results DataFrame ---")
display(results_df.head())

Processing video: normanniles1_2025-10-20-10-04-45.mp4
Objects detected in normanniles1_2025-10-20-10-04-45.mp4: {'car_left': 177, 'car_right': 225, 'truck_left': 26, 'truck_right': 37, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 3}
Congestion Enter Rating: light delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-05-45.mp4
Objects detected in normanniles1_2025-10-20-10-05-45.mp4: {'car_left': 17, 'car_right': 178, 'truck_left': 5, 'truck_right': 51, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 2}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-06-45.mp4
Objects detected in normanniles1_2025-10-20-10-06-45.mp4: {'car_left': 163, 'car_right': 228, 'truck_left': 21, 'truck_right': 9, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-07-45.mp4
Objects detected in normanniles1_2025-10-20-10-07-45.mp4: {'car_left': 82, 'car_right': 262, 'truck_left': 9, 'truck_right': 17, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 13}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-08-45.mp4
Objects detected in normanniles1_2025-10-20-10-08-45.mp4: {'car_left': 232, 'car_right': 353, 'truck_left': 42, 'truck_right': 43, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 1, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-09-45.mp4
Objects detected in normanniles1_2025-10-20-10-09-45.mp4: {'car_left': 121, 'car_right': 156, 'truck_left': 1, 'truck_right': 34, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 70, 'bus_right': 50}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-10-45.mp4
Objects detected in normanniles1_2025-10-20-10-10-45.mp4: {'car_left': 261, 'car_right': 422, 'truck_left': 55, 'truck_right': 30, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 7, 'bus_right': 0}
Congestion Enter Rating: light delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-11-45.mp4
Objects detected in normanniles1_2025-10-20-10-11-45.mp4: {'car_left': 164, 'car_right': 297, 'truck_left': 21, 'truck_right': 21, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-12-45.mp4
Objects detected in normanniles1_2025-10-20-10-12-45.mp4: {'car_left': 194, 'car_right': 393, 'truck_left': 105, 'truck_right': 37, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 1}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-13-45.mp4
Objects detected in normanniles1_2025-10-20-10-13-45.mp4: {'car_left': 325, 'car_right': 718, 'truck_left': 106, 'truck_right': 51, 'motorcycle_left': 1, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 64, 'bus_right': 6}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-14-45.mp4
Objects detected in normanniles1_2025-10-20-10-14-45.mp4: {'car_left': 172, 'car_right': 267, 'truck_left': 70, 'truck_right': 29, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 5, 'bus_right': 6}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-16-45.mp4
Objects detected in normanniles1_2025-10-20-10-16-45.mp4: {'car_left': 351, 'car_right': 756, 'truck_left': 63, 'truck_right': 45, 'motorcycle_left': 3, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: light delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-17-45.mp4
Objects detected in normanniles1_2025-10-20-10-17-45.mp4: {'car_left': 350, 'car_right': 336, 'truck_left': 51, 'truck_right': 29, 'motorcycle_left': 2, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 43, 'bus_right': 49}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-18-45.mp4
Objects detected in normanniles1_2025-10-20-10-18-45.mp4: {'car_left': 471, 'car_right': 682, 'truck_left': 5, 'truck_right': 110, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: light delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-19-45.mp4
Objects detected in normanniles1_2025-10-20-10-19-45.mp4: {'car_left': 185, 'car_right': 529, 'truck_left': 63, 'truck_right': 39, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-20-45.mp4
Objects detected in normanniles1_2025-10-20-10-20-45.mp4: {'car_left': 408, 'car_right': 493, 'truck_left': 11, 'truck_right': 50, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-21-45.mp4
Objects detected in normanniles1_2025-10-20-10-21-45.mp4: {'car_left': 220, 'car_right': 483, 'truck_left': 77, 'truck_right': 46, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 40, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-22-45.mp4
Objects detected in normanniles1_2025-10-20-10-22-45.mp4: {'car_left': 432, 'car_right': 539, 'truck_left': 137, 'truck_right': 40, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 9, 'bus_right': 1}
Congestion Enter Rating: light delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-23-45.mp4
Objects detected in normanniles1_2025-10-20-10-23-45.mp4: {'car_left': 335, 'car_right': 894, 'truck_left': 16, 'truck_right': 15, 'motorcycle_left': 10, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 20, 'bus_right': 25}
Congestion Enter Rating: light delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-24-45.mp4
Objects detected in normanniles1_2025-10-20-10-24-45.mp4: {'car_left': 422, 'car_right': 778, 'truck_left': 138, 'truck_right': 105, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 3, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-25-45.mp4
Objects detected in normanniles1_2025-10-20-10-25-45.mp4: {'car_left': 419, 'car_right': 708, 'truck_left': 95, 'truck_right': 154, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 6, 'bus_right': 78}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-26-45.mp4
Objects detected in normanniles1_2025-10-20-10-26-45.mp4: {'car_left': 465, 'car_right': 738, 'truck_left': 45, 'truck_right': 71, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 68, 'bus_right': 58}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-27-45.mp4
Objects detected in normanniles1_2025-10-20-10-27-45.mp4: {'car_left': 456, 'car_right': 620, 'truck_left': 50, 'truck_right': 12, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-28-45.mp4
Objects detected in normanniles1_2025-10-20-10-28-45.mp4: {'car_left': 554, 'car_right': 608, 'truck_left': 110, 'truck_right': 98, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 60, 'bus_right': 59}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-29-45.mp4
Objects detected in normanniles1_2025-10-20-10-29-45.mp4: {'car_left': 785, 'car_right': 931, 'truck_left': 58, 'truck_right': 138, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-30-45.mp4
Objects detected in normanniles1_2025-10-20-10-30-45.mp4: {'car_left': 1076, 'car_right': 1001, 'truck_left': 4, 'truck_right': 30, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 2}
Congestion Enter Rating: heavy delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-31-45.mp4
Objects detected in normanniles1_2025-10-20-10-31-45.mp4: {'car_left': 537, 'car_right': 947, 'truck_left': 151, 'truck_right': 127, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 1}
Congestion Enter Rating: heavy delay, Congestion Exit Rating: moderate delay
Processing video: normanniles1_2025-10-20-10-32-45.mp4
Objects detected in normanniles1_2025-10-20-10-32-45.mp4: {'car_left': 534, 'car_right': 874, 'truck_left': 114, 'truck_right': 112, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 1, 'person_right': 0, 'bus_left': 49, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-33-45.mp4
Objects detected in normanniles1_2025-10-20-10-33-45.mp4: {'car_left': 641, 'car_right': 950, 'truck_left': 40, 'truck_right': 89, 'motorcycle_left': 8, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 71, 'bus_right': 63}
Congestion Enter Rating: heavy delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-34-45.mp4
Objects detected in normanniles1_2025-10-20-10-34-45.mp4: {'car_left': 517, 'car_right': 821, 'truck_left': 12, 'truck_right': 16, 'motorcycle_left': 3, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-35-45.mp4
Objects detected in normanniles1_2025-10-20-10-35-45.mp4: {'car_left': 182, 'car_right': 682, 'truck_left': 35, 'truck_right': 43, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: light delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-10-59-45.mp4
Objects detected in normanniles1_2025-10-20-10-59-45.mp4: {'car_left': 600, 'car_right': 907, 'truck_left': 120, 'truck_right': 40, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-00-45.mp4
Objects detected in normanniles1_2025-10-20-11-00-45.mp4: {'car_left': 489, 'car_right': 705, 'truck_left': 7, 'truck_right': 66, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 1}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-01-45.mp4
Objects detected in normanniles1_2025-10-20-11-01-45.mp4: {'car_left': 580, 'car_right': 740, 'truck_left': 87, 'truck_right': 38, 'motorcycle_left': 0, 'motorcycle_right': 1, 'person_left': 1, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-02-45.mp4
Objects detected in normanniles1_2025-10-20-11-02-45.mp4: {'car_left': 586, 'car_right': 762, 'truck_left': 19, 'truck_right': 55, 'motorcycle_left': 2, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 8, 'bus_right': 0}
Congestion Enter Rating: heavy delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-03-45.mp4
Objects detected in normanniles1_2025-10-20-11-03-45.mp4: {'car_left': 903, 'car_right': 927, 'truck_left': 39, 'truck_right': 19, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 61}
Congestion Enter Rating: moderate delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-04-45.mp4
Objects detected in normanniles1_2025-10-20-11-04-45.mp4: {'car_left': 595, 'car_right': 680, 'truck_left': 151, 'truck_right': 67, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 1, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: heavy delay, Congestion Exit Rating: moderate delay
Processing video: normanniles1_2025-10-20-11-05-45.mp4
Objects detected in normanniles1_2025-10-20-11-05-45.mp4: {'car_left': 708, 'car_right': 846, 'truck_left': 71, 'truck_right': 421, 'motorcycle_left': 1, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 1}
Congestion Enter Rating: moderate delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-06-45.mp4
Objects detected in normanniles1_2025-10-20-11-06-45.mp4: {'car_left': 691, 'car_right': 842, 'truck_left': 45, 'truck_right': 13, 'motorcycle_left': 1, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: heavy delay, Congestion Exit Rating: light delay
Processing video: normanniles1_2025-10-20-11-07-45.mp4
Objects detected in normanniles1_2025-10-20-11-07-45.mp4: {'car_left': 706, 'car_right': 1219, 'truck_left': 34, 'truck_right': 7, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-08-45.mp4
Objects detected in normanniles1_2025-10-20-11-08-45.mp4: {'car_left': 664, 'car_right': 842, 'truck_left': 0, 'truck_right': 68, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: moderate delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-09-45.mp4
Objects detected in normanniles1_2025-10-20-11-09-45.mp4: {'car_left': 677, 'car_right': 1001, 'truck_left': 65, 'truck_right': 95, 'motorcycle_left': 4, 'motorcycle_right': 1, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: moderate delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-10-45.mp4
Objects detected in normanniles1_2025-10-20-11-10-45.mp4: {'car_left': 785, 'car_right': 1032, 'truck_left': 76, 'truck_right': 66, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: light delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-11-45.mp4
Objects detected in normanniles1_2025-10-20-11-11-45.mp4: {'car_left': 580, 'car_right': 1026, 'truck_left': 78, 'truck_right': 41, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 1}
Congestion Enter Rating: heavy delay, Congestion Exit Rating: moderate delay
Processing video: normanniles1_2025-10-20-11-12-45.mp4
Objects detected in normanniles1_2025-10-20-11-12-45.mp4: {'car_left': 631, 'car_right': 936, 'truck_left': 75, 'truck_right': 79, 'motorcycle_left': 1, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 31, 'bus_right': 0}
Congestion Enter Rating: light delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-13-45.mp4
Objects detected in normanniles1_2025-10-20-11-13-45.mp4: {'car_left': 794, 'car_right': 1433, 'truck_left': 36, 'truck_right': 9, 'motorcycle_left': 3, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: moderate delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-14-45.mp4
Objects detected in normanniles1_2025-10-20-11-14-45.mp4: {'car_left': 526, 'car_right': 783, 'truck_left': 35, 'truck_right': 109, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-15-45.mp4
Objects detected in normanniles1_2025-10-20-11-15-45.mp4: {'car_left': 683, 'car_right': 894, 'truck_left': 136, 'truck_right': 42, 'motorcycle_left': 5, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: moderate delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-16-45.mp4
Objects detected in normanniles1_2025-10-20-11-16-45.mp4: {'car_left': 701, 'car_right': 1441, 'truck_left': 29, 'truck_right': 2, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-17-45.mp4
Objects detected in normanniles1_2025-10-20-11-17-45.mp4: {'car_left': 603, 'car_right': 774, 'truck_left': 109, 'truck_right': 109, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: free flowing, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-18-45.mp4
Objects detected in normanniles1_2025-10-20-11-18-45.mp4: {'car_left': 736, 'car_right': 1079, 'truck_left': 87, 'truck_right': 64, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 1}
Congestion Enter Rating: moderate delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-19-45.mp4
Objects detected in normanniles1_2025-10-20-11-19-45.mp4: {'car_left': 825, 'car_right': 965, 'truck_left': 2, 'truck_right': 31, 'motorcycle_left': 0, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: heavy delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-20-45.mp4
Objects detected in normanniles1_2025-10-20-11-20-45.mp4: {'car_left': 747, 'car_right': 1200, 'truck_left': 33, 'truck_right': 25, 'motorcycle_left': 3, 'motorcycle_right': 0, 'person_left': 0, 'person_right': 0, 'bus_left': 0, 'bus_right': 0}
Congestion Enter Rating: heavy delay, Congestion Exit Rating: free flowing
Processing video: normanniles1_2025-10-20-11-21-45.mp4

,video_filename,congestion_enter_rating,congestion_exit_rating,car_left,car_right,truck_left,truck_right,motorcycle_left,motorcycle_right,person_left,person_right,bus_left,bus_right
0,normanniles1_2025-10-20-10-04-45.mp4,light delay,free flowing,177,225,26,37,0,0,0,0,0,3
1,normanniles1_2025-10-20-10-05-45.mp4,free flowing,free flowing,17,178,5,51,0,0,0,0,0,2
2,normanniles1_2025-10-20-10-06-45.mp4,free flowing,free flowing,163,228,21,9,0,0,0,0,0,0
3,normanniles1_2025-10-20-10-07-45.mp4,free flowing,free flowing,82,262,9,17,0,0,0,0,0,13
4,normanniles1_2025-10-20-10-08-45.mp4,free flowing,free flowing,232,353,42,43,0,0,0,0,1,0

In [14]:
output_csv_path = 'video_analysis_results.csv'
results_df.to_csv(output_csv_path, index=False)
print(f"Results saved to {output_csv_path}")

Results saved to video_analysis_results.csv

# Objects counter

In [ ]:
"""
generate an initial counts sheet for the objects by setting ranges for the
number of objects and the classes in the training data and classify
the test data based on them.

check for  how to count the accurcy and f1-score
"""

# Objects dataset

In [ ]:
"""
video_list = []

for images in in the video:
    detect the most important 15 objects for each frame
    video_list.append(objects)

with open (video):
    create a csv file for the video with the objects name and score
"""

# Frame classification setup

In [ ]:
"""
build a Keras model to classify the frames into the required classes for the density of traffic
then find the most common to get the density of traffic for the full video.
"""